### ISSUE TITLE
建议有个高可用的例子

### ISSUE THREAD

**Issue by qinzdc** [cloudframeworks-springcloud/user-guide-springcloud#26]
发现了些问题。
现在是注册服务->configserver,实际反的吧， 应该是configserver注册到中心，作为微服务提供配置~
建议出一套各个模块都是高可用的例子，这样对大家帮助大不烧

**Comment by elvis2002** [comment]
从我的理解配置中心是包含所有的配置信息, 当然也包含注册中心的服务地址了；每个服务都是通过spring-cloud-starter-config动态获取配置中心信息的。
建议出一套各个模块都是高可用的例子？是说的springcloud各个组件如何使用吗？

**Comment by smarthadron** [comment]
issue closed：p
