### ISSUE TITLE
一键部署运行不起来

### ISSUE THREAD

**Issue by 8debug** [cloudframeworks-springcloud/user-guide-springcloud#38]

**Comment by 297179121** [comment]
> Window10 64位专业版
> 执行一键命令，容器都运行起来了，但是gateway服务启动失败，容器日志报错：
> `Could not locate PropertySource and the fail fast property is set, failing`，还有几个容器也是这类日志信息。
> demo的运行对学习很重要，一键部署的脚本代码中的镜像是楼主已经上传到DockerHub上，这样没有直接在本地运行方便快捷，我忙活了一个小时还没运行起来。项目中还些镜像也是楼主封装好放在仓库里的，例如：config下的Dockerfile中`FROM goodrainapps/maven:jdk8-alpine`，不知道这个镜像楼主做了多少修改，如果我换成别的会不会有影响目前都是未知。本以为是个快速上手教程，现在我还没运行起来。

**Comment by 297179121** [comment]
Window10 64位专业版
执行一键命令，容器都运行起来了，但是gateway服务启动失败，容器日志报错：
Could not locate PropertySource and the fail fast property is set, failing，还有几个容器也是这类日志信息。
demo的运行对学习很重要，一键部署的脚本代码中的镜像是楼主已经上传到DockerHub上，这样没有直接在本地运行方便快捷，我忙活了一个小时还没运行起来。项目中还些镜像也是楼主封装好放在仓库里的，例如：config下的Dockerfile中FROM goodrainapps/maven:jdk8-alpine，不知道这个镜像楼主做了多少修改，如果我换成别的会不会有影响目前都是未知。本以为是个快速上手教程，现在我还没运行起来。
